name: Donate
highlighter: true
#relative_permalinks: true

permalink: /:year/:title.html

include: [".htaccess"]

exclude: ["ctl","page"]

#defaults for donate pages
default-currency-symbol: "$"
amounts: [15, 35, 50, 100, 250, 500, 1000]


client: bsd
author: BSD