name: Donate
highlighter: rouge
relative_permalinks: true

permalink: /:year/:title.html

include: [".htaccess","ctl"]
exclude: ["_minjs"]

#defaults for donate pages
default-currency-symbol: "$"
amounts: [15, 35, 50, 100, 250, 500, 1000]


client: bsd
author: BSD